### PR TITLE
AUTH_LDAP_SERVER_URI callback function takes an optional request argu…

### PR DESCRIPTION
**Pull request by hetsch**
…ment

### CODE REVIEW

**Comment by hetsch** [comment]
I'm not very happy with the part and catching with `TypeError`:

    try:
        uri = uri(self._request)
    except TypeError:
        uri = uri()

One other solution that came to my mind was using `'request' in inspect.getargspec(uri).args` or `inspect.signature(uri)`. For my taste, using the introspection API in this situation is like using a sledgehammer to crack a nut ...

**Comment by jdufresne** [comment]
I recommend using Django's `inspect.py` module to check if the callable accepts `request`:

https://github.com/django/django/blob/1.11/django/utils/inspect.py

This strategy has been used internally by Django to great success. Here is one example:

https://github.com/django/django/commit/be6ca89396c031619947921c81b8795d816e3285

I think if the callable does not accept `request` a deprecation warning should be emitted so library users know their code must change to remain compatible with future versions.

**Comment by hetsch** [comment]
Great, thank's for links. You never stop learning. I was somehow afraid that the introspection might be too costly, performance wise.

What do you think if I use a message like `Found a deprecated method signature for the AUTH_LDAP_SERVER_URI callback. From now on, the callback takes an additional request parameter`. I don't want to offend someone with my wonky english grammar :)

**Comment by jdufresne** [comment]
That works for me. Thanks!

**Comment by hetsch** [comment]
Sorry to bug you again. It seems like django's `get_func_args` is not well suited for our usecase. Travis is spitting venom for tox environment `py27-django111`. This might happen because [get_func_args v1.11](https://github.com/django/django/blob/1.11.14/django/utils/inspect.py#L34) slightly changed to [get_func_args v2.0](https://github.com/django/django/blob/2.0/django/utils/inspect.py#L4).

This hurts us because in `py27-dango111` they use `argspec.args` to evaluate the function parameter but they drop the first parameter of each function with `return argspec.args[1:]  # ignore 'self'` (see [get_func_args v1.11](https://github.com/django/django/blob/1.11.14/django/utils/inspect.py#L37)). This makes sense if dealing with object or class methods, but with lambda or casual functions (without a self parameter) this simply drops the "real" first argument. The `Python 3` versions with `django>=2.0` using `inspect.signature` works fine. I don't know if the django guys did this by intention or if this bug. This leads me to the conclusion that if we want to support `py27-dango111`, we have to make a utility function based on [get_func_args v1.11](https://github.com/django/django/blob/1.11.14/django/utils/inspect.py#L34) but without slicing the first argument. I hope you understand what I mean that you might come up with a better idea.

**Comment by hetsch** [comment]
A much better fit ... Muchas gracias!

**Comment by jdufresne** [comment]
Merged as b2a7f324bc743fabb26c2eee3c5793594c5fb1f6. Thanks for the contribution!

**Pull request closed without merging**
